# SPDX-License-Identifier: GPL-2.0
vfio-platform-calxedaxgmac-y := vfio_platform_calxedaxgmac.o
vfio-platform-ahci-y := vfio_platform_ahci.o
vfio-platform-xhci-y := vfio_platform_xhci.o
vfio-platform-xor-v2-y := vfio_platform_xor_v2.o
vfio-platform-sdhci-y := vfio_platform_sdhci.o
vfio-platform-amdxgbe-y := vfio_platform_amdxgbe.o

obj-$(CONFIG_VFIO_PLATFORM_CALXEDAXGMAC_RESET) += vfio-platform-calxedaxgmac.o
obj-$(CONFIG_VFIO_PLATFORM_AHCI_RESET) += vfio-platform-ahci.o
obj-$(CONFIG_VFIO_PLATFORM_XHCI_RESET) += vfio-platform-xhci.o
obj-$(CONFIG_VFIO_PLATFORM_XOR_V2_RESET) += vfio-platform-xor-v2.o
obj-$(CONFIG_VFIO_PLATFORM_SDHCI_RESET) += vfio-platform-sdhci.o
obj-$(CONFIG_VFIO_PLATFORM_AMDXGBE_RESET) += vfio-platform-amdxgbe.o
obj-$(CONFIG_VFIO_PLATFORM_BCMFLEXRM_RESET) += vfio_platform_bcmflexrm.o
